language: python
python:
- '2.7'
env:
  global:
  - GAE_DIR=/tmp/gae
  - EMAIL=appsamblea@gmail.com
  - secure: PqHVN9cMilkhLnsb2SyyWVwmV15ig/ulj/AXLgpy6+fgcfK9d8XBwe4M2ahs3GfoD1xti/ujsNdQh+3tkfBXV26m5L0PnscbX4MQoUNI35+rEr3Jv/Fb1VKt06IBKvWZJqOFeYkuSdlRqiI/bfcuw4FvqhmOtoHOaEpQj943EjE=
before_install:
- |
  test -e $GAE_DIR ||  (mkdir -p $GAE_DIR &&  wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.15.zip -q -O /tmp/gae.zip && unzip -q /tmp/gae.zip -d $GAE_DIR)
install:
- pip install -r requirements.txt
before_script: 
script:
- python test.py
after_success: ./after_success.sh
